Repository SpandanM110/De-SchoolMate, pull requests merged in 2023-10, with the labels that each got.

#14 Fixes issue #13
  Frontend/Landing Page/index.html
  index.html
Labels: hacktoberfest-accepted

#24 Hero-photo-added
  Frontend/Landing Page/style.css
  Images/pexels-kobe-1516440.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 Changes made in navbar and pill Button added along with some animations on hover.
  Frontend/Landing Page/index.html
  Frontend/Landing Page/style.css
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted

#28 Improve navbar styling for more appealing design
  Frontend/Landing Page/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#30 Edited Features Section
  Frontend/Landing Page/style.css
  Frontend/Media/calendar.png
  Frontend/Media/notes.png
  Frontend/Media/open-book.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 pulled my first PR
  Frontend/Landing Page/index.html
  Frontend/Landing Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#35 Responsive nav
  Frontend/Landing Page/style.css
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 Navabar changes
  Frontend/Landing Page/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 added home button to every page
  Frontend/Calender/index.html
  Frontend/Calender/script.js
  Frontend/Calender/styles.css
  Frontend/Feature Menu/script.js
  Frontend/Feature Menu/style.css
  Frontend/Note making/index.html
  Frontend/Note making/script.js
  Frontend/Note making/style.css
  Frontend/Timer/index.html
  Frontend/Timer/script.js
  Frontend/Timer/styles.css
  Frontend/ToDo List v2/CSS/main.css
  Frontend/ToDo List v2/JS/main.js
  Frontend/ToDo List v2/index.html
  Frontend/Tutorial Search/index.html
  Frontend/Tutorial Search/script.js
  Frontend/Tutorial Search/style.css
  Frontend/book search/css/style.css
  Frontend/book search/index.html
  Frontend/book search/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#45 Feat: Improved feature page UI Gallery Look
  Frontend/Feature Menu/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 About us Section
  Frontend/Landing Page/style.css
  Frontend/Media/Study.jpg
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#49 fix: footer changes
  Frontend/Feature Menu/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#48 Fixed opening in other tab isssue.
  Frontend/Feature Menu/script.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#58 Pomodaro Timer CSS Improvement
  Frontend/Timer/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#61 Navbar responsive Fix issue #60
  Frontend/Landing Page/style.css
  index.html
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#68 meta content and description is added
  .vscode/settings.json
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#69 Uniform UI and CSS Changes
  Frontend/Calender/styles.css
  Frontend/Note making/style.css
  Frontend/Timer/index.html
  Frontend/Timer/styles.css
  Frontend/ToDo List v2/CSS/main.css
  Frontend/Tutorial Search/style.css
  Frontend/book search/css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#71 Background colours updates
  Frontend/ToDo List v2/CSS/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#72 created back-to-top button
  Frontend/Landing Page/style.css
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#77 added social media icons to footer
  Frontend/Landing Page/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#79 tilt on hover effect added
  Frontend/Landing Page/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#86 New Favicon is added
  .DS_Store
  Frontend/Landing Page/style.css
  Images/.DS_Store
  Images/favicons/.DS_Store
  Images/favicons/favicon-192.png
  Images/favicons/favicon-512.png
  Images/favicons/favicon-64.png
  Images/img/.DS_Store
  Images/img/Hero.png
  Images/img/about.png
  Images/img/book.png
  Images/img/calendar.png
  Images/img/github.svg
  Images/img/logo-bottom.png
  Images/img/logo-header.png
  Images/img/notes.png
  Images/pexels-kobe-1516440.jpg
  index.html
  manifest.webmanifest
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#89 Fix/gitignore filename #84
  .gitIgnore
  .gitignore
Labels: hacktoberfest, hacktoberfest-accepted

#83 Make the background static plus modified the landing page
  Frontend/Landing Page/index.html
  Frontend/Landing Page/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#92 Text Visibility on Hover on Open APP page Solved
  Frontend/Feature Menu/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#93 Fix some bugs
  Frontend/Landing Page/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#95 Fix the bug + Design the features menu
  Frontend/Feature Menu/index.html
  Frontend/Feature Menu/style.css
  Frontend/Landing Page/index.html
  Frontend/Landing Page/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#96 fix: added github link in footer social handle
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
